<?php

/**
 * @file
 *  A module that provides a checkbox field to be used for subscribing to
 *  newsletters that can be attached to any entity type form.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function newsletter_field_field_formatter_info_alter(array &$info) {
  // The boolean field formatter should be available for our field too.
  $info['boolean']['field_types'][] = 'newsletter';
}
